### ISSUE TITLE
async_urequests should respect content length header

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [Carglglz/asyncmd#1]
[Line 21 of async_urequests.py](https://github.com/Carglglz/asyncmd/blob/74ec11167ae6477ba924b5c020522e3cfb82fd74/async_modules/async_urequests/async_urequests.py#L21C17-L21C53)
* `self._cached = await self.raw.read()`

There exist a [upstream bug](https://github.com/micropython/micropython-lib/issues/546) and a [pull request](https://github.com/micropython/micropython-lib/pull/602)

**Comment by Carglglz** [comment]
That makes sense, since upstream `urequests.py` was the reference. 
Did you test that PR? If that works I could push the changes or accept a PR 👍🏼

**Comment by GM-Script-Writer-62850** [comment]
I have not tested it in `async_urequests` yet, i was just looking over the code and i checked to see if the issue i found before looked to be present in this port

that PR is based on a patch i put in the bug report

**Comment by GM-Script-Writer-62850** [comment]
I just confirmed the issue and that the patch i posted in the bug report works

BTW i ended up removing ssl support as micropython asyncio.open_connection only supports 2 arguments
