### ISSUE TITLE
/package.json doesn't parse

### ISSUE THREAD

**Issue by swork** [Carglglz/asyncmd#2]
The "urls" list in top-level package.json ends with a comma, so doesn't parse.

**Comment by swork** [comment]
Looks like the "deps" value needs to be pairs, also, rather than bare strings. Please accept apologies for filing the issue before completely testing the results.

**Comment by Carglglz** [comment]
@swork Thanks for the report and the PR, I guess I should review the rest of package.json files too and check if wether they work. 😅
