### ISSUE TITLE
help getting schedule.py to work

### ISSUE THREAD

**Issue by bstin** [Carglglz/asyncmd#5]
Hi,

I'm trying to figure out how schedule.py works, but I'm having trouble. Here is my simple test case:

```
#main.py
import aioschedule
import aioctl
import time
import asyncio


#@aioschedule.schedule_task(start_in=10, repeat=60) # decorators should be used in this order
@aioctl.aiotask
async def my_task(var):
    print(f"Hello, {var}!")


async def main():
    aioctl.add(my_task, "Foo", name="my_task")
    aioschedule.schedule("my_task", start_in=time.localtime(time.time() + 1), repeat=3)
    aioctl.add(aioschedule.schedule_loop)

# Run the main coroutine
asyncio.run(main())
```
The error produced is:

> _AIOCTL_GROUP.results[name] = _AIOCTL_GROUP.tasks[name].task.data
> AttributeError: '_asyncio.Task' object has no attribute 'data'

**Comment by Carglglz** [comment]
@bstin Do you have the full traceback? / error line numbers?

In any case you need to await `aioctl.tasks`  e.g. 

```py

async def main():
    aioctl.add(my_task, "Foo", name="my_task")
    aioschedule.schedule("my_task", start_in=time.localtime(time.time() + 1), repeat=3)
    aioctl.add(aioschedule.schedule_loop)
    await asyncio.gather(*aioctl.tasks())

```

see this example https://github.com/Carglglz/asyncmd/blob/main/docs/aioschedule.md#watcher_loop

**Comment by bstin** [comment]
Thank you. 

I was missing `await asyncio.gather(*aioctl.tasks())`

Working nicely
